name: Run data export

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 1 * * *"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: curl --fail 'https://ggpk.exposed/version?poe=2' | sed -r 's|.*/([0-9](\.[0-9]+)+)/$|\1|' > version.txt
      - run: git ls-remote https://github.com/poe-tool-dev/dat-schema.git refs/heads/main > schema.txt
      - id: version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
      - id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          commit_message: "[skip ci] Version ${{ steps.version.outputs.version }}"
    outputs:
      changes_detected: ${{ steps.autocommit.outputs.changes_detected }}
      version: ${{ steps.version.outputs.version }}

  build:
    runs-on: ubuntu-latest
    needs: version
    if: github.event_name != 'schedule' || needs.version.outputs.changes_detected == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          path: poe2
      - name: checkout repoe
        uses: actions/checkout@v4.2.2
        with:
          repository: repoe-fork/repoe-fork
          path: RePoE
      - name: checkout pypoe
        uses: actions/checkout@v4.2.2
        with:
          repository: repoe-fork/pypoe
          path: PyPoE
      - run: pipx install 'poetry~=1.8'
      - name: setup python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"
          cache: poetry
      - name: clean poe2 dir
        run: find poe2/data '(' -name '*.json' -not -path '*/pob/*' -o -name '*.html' -o -name '*.txt' ')' -delete -print | wc -l
      - run: poetry install
        working-directory: RePoE
      - run: poetry run pypoe_schema_import -a stable --poe2 -u https://repoe-fork.github.io/dat-export/poe2/filtered.json
        working-directory: RePoE
      - name: update models
        run: |
          for i in *.schema.json
          do
            poetry run datamodel-codegen --input $i --input-file-type jsonschema --output ../model/${i/.schema.json/.py} --output-model-type pydantic_v2.BaseModel --disable-timestamp --use-double-quotes --enable-version-header
          done
        working-directory: RePoE/RePoE/schema
      - run: poetry run repoe all -l all --poe2 -o ../poe2/data
        working-directory: RePoE
      - name: generate index.html
        run: |
          find data -type d -exec tree {} -H '.' --dirsfirst -F -L 1 -T "RePoE - PoE2 version $(cat ../version.txt)" -I 'index.html|schema_doc*' --noreport --charset utf-8 -o {}/index.html \;
          find data -name index.html -exec sed -i 's|<h1>RePoE|<h1><a href="https://github.com/repoe-fork/repoe-fork">RePoE</a>|' {} \;
        working-directory: poe2
      - id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          repository: poe2
          commit_message: "[skip ci] Export ${{ needs.version.outputs.version }}"
      - if: github.event_name != 'schedule' || steps.autocommit.outputs.changes_detected == 'true'
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: poe2/data
    outputs:
      changes_detected: ${{ steps.autocommit.outputs.changes_detected }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'schedule' || needs.build.outputs.changes_detected == 'true'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4.0.5
